### PR TITLE
Fix plugin not working with 2019.3 EAP builds

### LINKED ISSUE #72: Error with WebStorm 2019.3 EAP
* **IDE name and version:** 
WebStorm 2019.3 EAP
Build #WS-193.2956.38, built on September 11, 2019
WebStorm EAP User
Expiration date: October 11, 2019
Runtime version: 11.0.4+12-b462.3 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-27-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 4062M
Cores: 4
Registry: 
Non-Bundled Plugins: 
* **Styled-components plugin version:** 
1.0.10

## Problem description:
An error occurs when attempting to type in some sections of styled components resulting in no output to the screen ie Typing doesn't work 

image

`java.lang.IllegalStateException
	at com.intellij.psi.impl.source.tree.injected.MultiHostRegistrarImpl.getResult(MultiHostRegistrarImpl.java:25)
	at com.intellij.styledComponents.StyledComponentsInjector.getInjectionResult(StyledComponentsInjector.kt:70)
	at com.intellij.styledComponents.StyledComponentsInjector.getLanguagesToInject(StyledComponentsInjector.kt:59)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:421)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.probeElementsUp(InjectedLanguageUtil.java:341)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:166)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.findInside(InjectedLanguageUtil.java:483)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.tryOffset(InjectedLanguageUtil.java:462)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.findInjectedElementNoCommit(InjectedLanguageUtil.java:442)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.findInjectedElementAt(InjectedLanguageManagerImpl.java:286)
	at com.intellij.codeInsight.highlighting.BraceHighlightingHandler.getInjectedFileIfAny(BraceHighlightingHandler.java:177)
	at com.intellij.codeInsight.highlighting.BraceHighlightingHandler.lambda$null$1(BraceHighlightingHandler.java:112)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1043)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:124)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:592)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:538)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:113)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:91)
	at com.intellij.codeInsight.highlighting.BraceHighlightingHandler.lambda$null$2(BraceHighlightingHandler.java:101)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:176)
	at com.intellij.codeInsight.highlighting.BraceHighlightingHandler.lambda$null$3(BraceHighlightingHandler.java:100)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1048)
	at com.intellij.codeInsight.highlighting.BraceHighlightingHandler.lambda$lookForInjectedAndMatchBracesInOtherThread$4(BraceHighlightingHandler.java:98)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:254)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

### PR DESCRIPTION
**Pull request by undeadcat**
`MultiHostRegistrarImpl` was a deprecated API, should have migrated away from it earlier.
Now it seems the working implementation was deleted in 2019.3.

Use `com.intellij.lang.javascript.injections.StringInterpolationErrorFilter`, it was adapted from this plugin.

Fixes #72

### CODE REVIEW

**Comment by undeadcat** [comment]
@mxstbr, Is it possible to give @denofevil permissions to review and merge PRs in the plugin repo? I'm not able to add him as a reviewer or add him to any of the teams.

I'm going to be less involved in the plugin in the future and Dennis has contributed to it already and is the WebStorm team lead.

**Comment by wijskinner** [comment]
Quick work! Thanks.

**Comment by undeadcat** [comment]
@prigara, Will you publish the plugin as well?
I don't have publish rights any more.

Thank you!

**Comment by denofevil** [comment]
@undeadcat thanks for the fix! I've uploaded the new version

**Pull request merged**
